---
abstract: 'Collection of Perl modules for Rinci and Riap'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci
requires:
  Class::Inspector: 0
  Data::Format::Pretty: 0
  Data::Format::Pretty::Console: 0.12
  Data::Format::Pretty::JSON: 0.03
  Data::Format::Pretty::YAML: 0.02
  Log::Any: 0
  Module::List: 0
  Perinci::Examples: 0.08
  Perinci::Sub::Wrapper: 0.19
  Riap: 1.1.10
  Rinci: 1.1.11
  SHARYANTO::Package::Util: 0
  Test::More: 0.96
  Tie::Cache: 0
  URI: 0
  perl: 5.010000
resources:
  homepage: http://metacpan.org/release/Perinci
  repository: http://github.com/sharyanto/perl-Perinci
version: 0.14
