---
abstract: 'Collection of Perl modules for Rinci and Riap'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::chdir: 0
  Module::Build: 0.3601
  Perinci::Examples: 0.08
  Perinci::Sub::DepChecker: 0
  Setup::File::Symlink: 0
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci
requires:
  Class::Inspector: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Format::Pretty: 0
  Data::Format::Pretty::Console: 0.12
  Data::Format::Pretty::JSON: 0.03
  Data::Format::Pretty::YAML: 0.02
  File::Flock: 0
  JSON: 0
  Log::Any: 0
  Module::List: 0
  Perinci::MetaAccessor::Default: 0
  Perinci::Sub::Wrapper: 0.25
  Perinci::Util: 0
  Riap: v1.1.14
  Rinci: v1.1.19
  SHARYANTO::Package::Util: 0
  Tie::Cache: 0
  URI: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Perinci
  repository: http://github.com/sharyanto/perl-Perinci
version: 0.25
